{{- if .Values.executeConfig.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: "job-execute"
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: "job-execute"
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
    kind: Deployment
    name: "job-execute"
  minReplicas: {{ .Values.executeConfig.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.executeConfig.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.executeConfig.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.executeConfig.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.executeConfig.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.executeConfig.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
