{{- if .Values.logsvrConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-logsvr
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: "job-logsvr"
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
data:
  application.yaml: |-
    spring:
      application:
        name: {{ include "common.names.fullname" . }}-logsvr
      data:
        mongodb:
          uri: {{ include "job.mongodb.connect.uri" . | quote }}
          database: "joblog"
    job:
      logsvr:
        mongodb:
          shard:
            enabled: {{ include "job.mongodb.useShardingCluster" . }}
    server:
      port: {{ .Values.logsvrConfig.containerPort }}
    management:
      metrics:
        tags:
          application: "job-logsvr"
  {{- end}}
