apiVersion: v2
name: "bk-job"
description: The BK-JOB is a ops script management and execution system with the capability of dealing with multiple tasks simultaneously.
type: application
version: 0.3.0-rc.25
appVersion: "3.6.0-rc.25"

dependencies:
- name: common
  version: 1.16.0
  repository: https://charts.bitnami.com/bitnami
- name: nginx-ingress-controller
  version: 9.2.6
  repository: https://charts.bitnami.com/bitnami
  condition: nginx-ingress-controller.enabled
- name: mariadb
  version: 11.0.10
  repository: https://charts.bitnami.com/bitnami
  condition: mariadb.enabled
- name: redis
  version: 16.11.3
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
- name: mongodb
  version: 12.1.16
  repository: https://charts.bitnami.com/bitnami
  condition: mongodb.enabled
- name: rabbitmq
  version: 10.1.5
  repository: https://charts.bitnami.com/bitnami
  condition: rabbitmq.enabled
