{{- if and (and .Values.frontendConfig.enabled .Values.gatewayConfig.enabled) (.Values.tencentCloudClbConfig.ingress.enabled) -}}
apiVersion: {{ template "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "common.names.fullname" . }}-tencent-cloud-clb
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: job-api-tencent-cloud-clb
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.tencentCloudClbConfig.ingress.annotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.tencentCloudClbConfig.ingress.annotations "context" $) | nindent 4 }}
    {{- end }}
spec:
  {{- if and .Values.ingress.ingressClassName (include "common.ingress.supportsIngressClassname" .) }}
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
  {{- end }}
  {{- if .Values.tencentCloudClbConfig.ingress.tls }}
  tls: {{- include "common.tplvalues.render" ( dict "value" .Values.tencentCloudClbConfig.ingress.tls "context" $) | nindent 2 -}}
  {{- end }}
  rules:
    - host: {{ include "job.web.domain" . }}
      http:
        paths:
          - path: "{{ include "job.url.pathRootPrefix" . }}/"
            pathType: ImplementationSpecific
            backend: {{- include "common.ingress.backend" (dict "serviceName" (printf "%s-frontend" (include "common.names.fullname" .)) "servicePort" .Values.frontendConfig.service.port "context" $)  | nindent 14 }}
          - path: "{{ include "job.url.pathRootPrefix" . }}/api/"
            pathType: ImplementationSpecific
            backend: {{- include "common.ingress.backend" (dict "serviceName" (printf "%s-gateway" (include "common.names.fullname" .)) "servicePort" .Values.gatewayConfig.service.port.http "context" $)  | nindent 14 }}
          - path: "{{ include "job.url.pathRootPrefix" . }}/iam/"
            pathType: ImplementationSpecific
            backend: {{- include "common.ingress.backend" (dict "serviceName" (printf "%s-gateway" (include "common.names.fullname" .)) "servicePort" .Values.gatewayConfig.service.port.http "context" $)  | nindent 14 }}
          - path: "{{ include "job.url.pathRootPrefix" . }}/job-"
            pathType: ImplementationSpecific
            backend: {{- include "common.ingress.backend" (dict "serviceName" (printf "%s-gateway" (include "common.names.fullname" .)) "servicePort" .Values.gatewayConfig.service.port.http "context" $)  | nindent 14 }}
          - path: "{{ include "job.url.pathRootPrefix" . }}/user/"
            pathType: ImplementationSpecific
            backend: {{- include "common.ingress.backend" (dict "serviceName" (printf "%s-gateway" (include "common.names.fullname" .)) "servicePort" .Values.gatewayConfig.service.port.http "context" $)  | nindent 14 }}
          - path: "{{ include "job.url.pathRootPrefix" . }}/logout"
            pathType: ImplementationSpecific
            backend: {{- include "common.ingress.backend" (dict "serviceName" (printf "%s-gateway" (include "common.names.fullname" .)) "servicePort" .Values.gatewayConfig.service.port.http "context" $)  | nindent 14 }}
{{- end }}
