spring:
  application:
    name: bk-job-op
  profiles:
    active: dev
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: password
      database: 0
      lettuce:
        pool:
          min-idle: 5
          max-idle: 10
          max-active: 8
          max-wait: 1ms
        shutdown-timeout: 100ms
  ai:
    mcp:
      server:
        name: bk-job-op    # MCP服务器名称
        version: 1.0.0                # 服务器版本号
        type: ASYNC #异步
        stdio: false

# HTTP客户端配置
http:
  client:
    # 连接超时时间（秒）
    connect-timeout: 10
    # 读取超时时间（秒）
    read-timeout: 60

# Spring Boot Actuator 配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,beans,configprops
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
  info:
    env:
      enabled: true

# MCP认证配置
mcp:
  # 认证token
  auth:
    enabled: true
    apiKey: "api-key"

# BK API网关统一配置
bkApiGateway:
  # 默认apigw认证信息（默认正式环境的，若是想调用个别别的环境的网关，使用子项覆盖）
  bkAppCode: "bk-job-op"
  bkAppSecret: "bk-job-op-secret"
  
  # 调用bklog网关的配置
  bkLog:
    url: bklog.com
    retry-count: 3
    retry-interval: 3

bk:
  # BK-Log配置
  log:
    # 日志索引名称
    indices: ""
    # 索引集ID
    indexSetId: 100
    # 日志保存时间
    expireTime: 7
