{{- if .Values.gatewayConfig.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: "job-gateway"
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
data:
  application.yaml: |-
    spring:
      cloud:
        loadbalancer:
          cache:
            ttl: 20s
        stream:
          defaultBinder: jobCommon
          binders:
            jobCommon:
              type: rabbit
              environment:
                spring:
                  rabbitmq:
                    host: {{ include "job.rabbitmq.host" . }}
                    port: {{ include "job.rabbitmq.port" . }}
                    username: {{ include "job.rabbitmq.username" . }}
                    {{ if .Values.externalRabbitMQ.existingPasswordSecret }}
                    password: {{ .Values.externalRabbitMQ.existingPasswordKey | default "rabbitmq-password" | printf "${%s}" }}
                    {{- else -}}
                    password: ${rabbitmq-password}
                    {{- end }}
                    virtual-host: {{ include "job.rabbitmq.vhost" . }}
        gateway:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
          routes:
            {{- if eq .Values.deploy.mode "standard" }}
            - id: job-logout
              uri: lb://job-gateway
              predicates:
                - Path= /logout
              filters:
                - Logout
            - id: job-manage-web
              uri: lb://job-manage
              predicates:
                - Path= /job-manage/web/**
              filters:
                - Authorize
                - CsrfCheck
                - StripPrefix=1
                - AddWebLangHeader
            - id: job-crontab-web
              uri: lb://job-crontab
              predicates:
                - Path= /job-crontab/web/**
              filters:
                - Authorize
                - CsrfCheck
                - StripPrefix=1
                - AddWebLangHeader
            - id: job-execute-web
              uri: lb://job-execute
              predicates:
                - Path= /job-execute/web/**
              filters:
                - Authorize
                - CsrfCheck
                - StripPrefix=1
                - AddWebLangHeader
            - id: job-backup-web
              uri: lb://job-backup
              predicates:
                - Path= /job-backup/web/**
              filters:
                - Authorize
                - CsrfCheck
                - StripPrefix=1
                - AddWebLangHeader
            - id: job-file-gateway-web
              uri: lb://job-file-gateway
              predicates:
                - Path= /job-file-gateway/web/**
              filters:
                - Authorize
                - CsrfCheck
                - StripPrefix=1
                - AddWebLangHeader
            - id: job-ticket-web
              uri: lb://job-manage
              predicates:
                - Path= /job-ticket/web/**
              filters:
                - Authorize
                - CsrfCheck
                - StripPrefix=1
                - AddWebLangHeader
            - id: job-analysis-web
              uri: lb://job-analysis
              predicates:
                - Path= /job-analysis/web/**
              filters:
                - Authorize
                - CsrfCheck
                - StripPrefix=1
                - AddWebLangHeader

            - id: job-file-gateway-remote
              uri: lb://job-file-gateway
              predicates:
                - Path= /job-file-gateway/remote/**
              filters:
                - AuthorizeRemote
                - StripPrefix=1

            - id: job-manage-esb
              uri: lb://job-manage
              predicates:
                - JobEsbV2Path=/api/job/v2/job-manage/{api_name}
              filters:
                - CheckTenant
                - CheckOpenApiJwt
                - SetPath=/esb/api/v2/{api_name}
                - RecordEsbAccessLog
                - AddEsbLangHeader

            - id: job-manage-esb-v3
              uri: lb://job-manage
              predicates:
                - Path=/api/job/v3/job-manage/{api_name}
              filters:
                - CheckTenant
                - CheckOpenApiJwt
                - SetPath=/esb/api/v3/{api_name}
                - RecordEsbAccessLog
                - AddEsbLangHeader

            - id: job-crontab-esb
              uri: lb://job-crontab
              predicates:
                - JobEsbV2Path=/api/job/v2/job-crontab/{api_name}
              filters:
                - CheckTenant
                - CheckOpenApiJwt
                - SetPath=/esb/api/v2/{api_name}
                - RecordEsbAccessLog
                - AddEsbLangHeader

            - id: job-crontab-esb-v3
              uri: lb://job-crontab
              predicates:
                - JobEsbV2Path=/api/job/v3/job-crontab/{api_name}
              filters:
                - CheckTenant
                - CheckOpenApiJwt
                - SetPath=/esb/api/v3/{api_name}
                - RecordEsbAccessLog
                - AddEsbLangHeader

            - id: job-execute-esb
              uri: lb://job-execute
              predicates:
                - JobEsbV2Path=/api/job/v2/job-execute/{api_name}
              filters:
                - CheckTenant
                - CheckOpenApiJwt
                - SetPath=/esb/api/v2/{api_name}
                - RecordEsbAccessLog
                - AddEsbLangHeader

            - id: job-execute-esb-v3
              uri: lb://job-execute
              predicates:
                - JobEsbV2Path=/api/job/v3/job-execute/{api_name}
              filters:
                - CheckTenant
                - CheckOpenApiJwt
                - SetPath=/esb/api/v3/{api_name}
                - RecordEsbAccessLog
                - AddEsbLangHeader

            - id: job-file-gateway-esb-v3
              uri: lb://job-file-gateway
              predicates:
                - JobEsbV2Path=/api/job/v3/job-file-gateway/{api_name}
              filters:
                - CheckTenant
                - CheckOpenApiJwt
                - SetPath=/esb/api/v3/{api_name}
                - RecordEsbAccessLog
                - AddEsbLangHeader

            - id: job-execute-esb-v4
              uri: lb://job-execute
              predicates:
                - JobEsbV2Path=/api/job/v4/job-execute/{api_name}
              filters:
                - CheckTenant
                - CheckOpenApiJwt
                - SetPath=/esb/api/v4/{api_name}
                - RecordEsbAccessLog
                - AddEsbLangHeader

            - id: job-manage-esb-v4
              uri: lb://job-manage
              predicates:
                - JobEsbV2Path=/api/job/v4/job-manage/{api_name}
              filters:
                - CheckTenant
                - CheckOpenApiJwt
                - SetPath=/esb/api/v4/{api_name}
                - RecordEsbAccessLog
                - AddEsbLangHeader

            - id: job-file-gateway-esb-v4
              uri: lb://job-file-gateway
              predicates:
                - JobEsbV2Path=/api/job/v4/job-file-gateway/{api_name}
              filters:
                - CheckTenant
                - CheckOpenApiJwt
                - SetPath=/esb/api/v4/{api_name}
                - RecordEsbAccessLog
                - AddEsbLangHeader

            - id: job-crontab-esb-v4
              uri: lb://job-crontab
              predicates:
                - JobEsbV2Path=/api/job/v4/job-crontab/{api_name}
              filters:
                - CheckTenant
                - CheckOpenApiJwt
                - SetPath=/esb/api/v4/{api_name}
                - RecordEsbAccessLog
                - AddEsbLangHeader

            - id: job-esb-v4
              uri: lb://job-assemble
              predicates:
                - Path=/api/job/v4/{module}/{api_name}
              filters:
                - CheckTenant
                - CheckOpenApiJwt
                - SetPath=/esb/api/v4/{api_name}
                - RecordEsbAccessLog
                - AddEsbLangHeader

            - id: job-file-gateway-iam
              uri: lb://job-file-gateway
              predicates:
                - Path=/iam/api/v1/resources/file_source
              filters:
                - RecordIamAccessLog
                - CheckTenant
                - AddEsbLangHeader

            - id: job-ticket-iam
              uri: lb://job-manage
              predicates:
                - Path=/iam/api/v1/resources/ticket
              filters:
                - RecordIamAccessLog
                - CheckTenant
                - AddEsbLangHeader

            - id: job-analysis-iam
              uri: lb://job-analysis
              predicates:
                - Path=/iam/api/v1/resources/dashboard_view
              filters:
                - RecordIamAccessLog
                - CheckTenant
                - AddEsbLangHeader

            - id: job-manage-iam
              uri: lb://job-manage
              predicates:
                - Path=/iam/api/v1/resources/script,/iam/api/v1/resources/task/template,/iam/api/v1/resources/task/plan,/iam/api/v1/resources/account,/iam/api/v1/resources/whitelist,/iam/api/v1/resources/script/public,/iam/api/v1/resources/tag
              filters:
                - RecordIamAccessLog
                - CheckTenant
                - AddEsbLangHeader

            - id: job-crontab-iam
              uri: lb://job-crontab
              predicates:
                - Path=/iam/api/v1/resources/cron/job
              filters:
                - RecordIamAccessLog
                - CheckTenant
                - AddEsbLangHeader

            - id: job-execute-iam
              uri: lb://job-execute
              predicates:
                - Path=/iam/api/v1/resources/execute/record
              filters:
                - RecordIamAccessLog
                - CheckTenant
                - AddEsbLangHeader
            {{- if eq (include "job.profileIsDev" .) "true" }}
            - id: job-execute-swagger
              uri: lb://job-execute
              predicates:
                - Path=/job-execute/swagger-ui/**,/job-execute/swagger-resources/**,/job-execute/v3/api-docs
              filters:
                - Authorize
                - CsrfCheck
                - StripPrefix=1
            - id: job-manage-swagger
              uri: lb://job-manage
              predicates:
                - Path=/job-manage/swagger-ui/**,/job-manage/swagger-resources/**,/job-manage/v3/api-docs
              filters:
                - Authorize
                - CsrfCheck
                - StripPrefix=1
            - id: job-analysis-swagger
              uri: lb://job-analysis
              predicates:
                - Path=/job-analysis/swagger-ui/**,/job-analysis/swagger-resources/**,/job-analysis/v3/api-docs
              filters:
                - Authorize
                - CsrfCheck
                - StripPrefix=1
            - id: job-crontab-swagger
              uri: lb://job-crontab
              predicates:
                - Path=/job-crontab/swagger-ui/**,/job-crontab/swagger-resources/**,/job-crontab/v3/api-docs
              filters:
                - Authorize
                - CsrfCheck
                - StripPrefix=1
            - id: job-backup-swagger
              uri: lb://job-backup
              predicates:
                - Path=/job-backup/swagger-ui/**,/job-backup/swagger-resources/**,/job-backup/v3/api-docs
              filters:
                - Authorize
                - CsrfCheck
                - StripPrefix=1
            - id: job-file-gateway-swagger
              uri: lb://job-file-gateway
              predicates:
                - Path=/job-file-gateway/swagger-ui/**,/job-file-gateway/swagger-resources/**,/job-file-gateway/v3/api-docs
              filters:
                - Authorize
                - CsrfCheck
                - StripPrefix=1
            - id: job-execute-swagger-service-op-esb
              uri: lb://job-execute
              predicates:
                - Path=/job-execute/service/**,/job-execute/op/**,/job-execute/esb/**
              filters:
                - Authorize
                - CsrfCheck
                - StripPrefix=1
            - id: job-manage-swagger-service-op-esb
              uri: lb://job-manage
              predicates:
                - Path=/job-manage/service/**,/job-manage/op/**,/job-manage/esb/**
              filters:
                - Authorize
                - CsrfCheck
                - StripPrefix=1
            - id: job-analysis-swagger-service-op-esb
              uri: lb://job-analysis
              predicates:
                - Path=/job-analysis/service/**,/job-analysis/op/**,/job-analysis/esb/**
              filters:
                - Authorize
                - CsrfCheck
                - StripPrefix=1
            - id: job-crontab-swagger-service-op-esb
              uri: lb://job-crontab
              predicates:
                - Path=/job-crontab/service/**,/job-crontab/op/**,/job-crontab/esb/**
              filters:
                - Authorize
                - CsrfCheck
                - StripPrefix=1
            - id: job-backup-swagger-service-op-esb
              uri: lb://job-backup
              predicates:
                - Path=/job-backup/service/**,/job-backup/op/**,/job-backup/esb/**
              filters:
                - Authorize
                - CsrfCheck
                - StripPrefix=1
            - id: job-file-gateway-swagger-service-op-esb
              uri: lb://job-file-gateway
              predicates:
                - Path=/job-file-gateway/service/**,/job-file-gateway/op/**,/job-file-gateway/esb/**
              filters:
                - Authorize
                - CsrfCheck
                - StripPrefix=1
            {{- end }}
            {{- else if eq .Values.deploy.mode "lite" }}
            - id: job-logout
              uri: lb://job-gateway
              predicates:
                - Path= /logout
              filters:
                - Logout
    
            - id: job-web
              uri: lb://job-assemble
              predicates:
                - Path= /job-manage/web/**,/job-crontab/web/**,/job-execute/web/**,/job-analysis/web/**,/job-backup/web/**,/job-logsvr/web/**,/job-file-gateway/web/**,/job-ticket/web/**
              filters:
                - Authorize
                - CsrfCheck
                - StripPrefix=1
                - AddWebLangHeader
    
            - id: job-file-gateway-remote
              uri: lb://job-assemble
              predicates:
                - Path= /job-file-gateway/remote/**
              filters:
                - AuthorizeRemote
                - StripPrefix=1

            - id: job-esb
              uri: lb://job-assemble
              predicates:
                - JobEsbV2Path=/api/job/v2/{module}/{api_name}
              filters:
                - CheckTenant
                - CheckOpenApiJwt
                - SetPath=/esb/api/v2/{api_name}
                - RecordEsbAccessLog
                - AddEsbLangHeader
    
            - id: job-esb-v3
              uri: lb://job-assemble
              predicates:
                - Path=/api/job/v3/{module}/{api_name}
              filters:
                - CheckTenant
                - CheckOpenApiJwt
                - SetPath=/esb/api/v3/{api_name}
                - RecordEsbAccessLog
                - AddEsbLangHeader
    
            - id: job-iam
              uri: lb://job-assemble
              predicates:
                - Path=/iam/api/v1/resources/**
              filters:
                - RecordIamAccessLog
                - CheckTenant
                - AddEsbLangHeader
            {{- end }}      
    job:
      gateway:
        login-exemption:
          enabled: {{ .Values.gatewayConfig.loginExemption.enabled | default false }}
          default-user: {{ .Values.gatewayConfig.loginExemption.defaultUser | default "admin" }}
          default-user-tenant-id: {{ .Values.gatewayConfig.loginExemption.defaultUserTenantId | default "default" }}
        user-map:
          {{- toYaml .Values.gatewayConfig.userMap | nindent 10 }}
        csrf-check:
          enabled: {{ .Values.gatewayConfig.csrfCheck.enabled }}
      bkApiGateway:
        enabled: {{ .Values.bkApiGatewayConfig.enabled | default false }}
        gatewayName: {{ .Values.bkApiGatewayConfig.gatewayName | default "bk-job" }}
        jwtPublicKey:
          get:
            failPolicy: {{ .Values.bkApiGatewayConfig.jwtPublicKey.failPolicy | default "retry" }}
    server:
      port: {{ .Values.gatewayConfig.containerPort.https }}
      http:
        enabled: true
        port: {{ .Values.gatewayConfig.containerPort.http }}
      ssl:
        enabled: true
        key-store-type: PKCS12
        key-store: "file:/data/job/cert/job_server.p12"
        key-store-password: ${keystore.password}
        key-alias: job_server.p12
        trust-store: "file:/data/job/cert/job_server.truststore"
        trust-store-password: ${truststore.password}
    management:
      server:
        port: {{ .Values.gatewayConfig.containerPort.management }}
{{- end }}
