{{- if .Values.gatewayConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: "job-gateway"
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
data:
  application.yaml: |-
    spring:
      cloud:
        gateway:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
          routes:
            - id: job-logout
              uri: lb://job-gateway
              predicates:
                - Path= /logout
              filters:
                - Logout
            - id: job-manage-web
              uri: lb://job-manage
              predicates:
                - Path= /job-manage/web/**
              filters:
                - Authorize
                - CsrfCheck
                - StripPrefix=1
                - AddWebLangHeader
            - id: job-crontab-web
              uri: lb://job-crontab
              predicates:
                - Path= /job-crontab/web/**
              filters:
                - Authorize
                - CsrfCheck
                - StripPrefix=1
                - AddWebLangHeader
            - id: job-execute-web
              uri: lb://job-execute
              predicates:
                - Path= /job-execute/web/**
              filters:
                - Authorize
                - CsrfCheck
                - StripPrefix=1
                - AddWebLangHeader
            - id: job-backup-web
              uri: lb://job-backup
              predicates:
                - Path= /job-backup/web/**
              filters:
                - Authorize
                - CsrfCheck
                - StripPrefix=1
                - AddWebLangHeader
            - id: job-file-gateway-web
              uri: lb://job-file-gateway
              predicates:
                - Path= /job-file-gateway/web/**
              filters:
                - Authorize
                - CsrfCheck
                - StripPrefix=1
                - AddWebLangHeader
            - id: job-ticket-web
              uri: lb://job-ticket
              predicates:
                - Path= /job-ticket/web/**
              filters:
                - Authorize
                - CsrfCheck
                - StripPrefix=1
                - AddWebLangHeader
            - id: job-analysis-web
              uri: lb://job-analysis
              predicates:
                - Path= /job-analysis/web/**
              filters:
                - Authorize
                - CsrfCheck
                - StripPrefix=1
                - AddWebLangHeader

            - id: job-file-gateway-remote
              uri: lb://job-file-gateway
              predicates:
                - Path= /job-file-gateway/remote/**
              filters:
                - AuthorizeRemote
                - StripPrefix=1

            - id: job-manage-esb
              uri: lb://job-manage
              predicates:
                - JobEsbV2Path=/api/job/v2/job-manage/{api_name}
              filters:
                - CheckEsbJwt
                - SetPath=/esb/api/v2/{api_name}
                - RecordEsbAccessLog
                - AddEsbLangHeader

            - id: job-manage-esb-v3
              uri: lb://job-manage
              predicates:
                - Path=/api/job/v3/job-manage/{api_name}
              filters:
                - CheckEsbJwt
                - SetPath=/esb/api/v3/{api_name}
                - RecordEsbAccessLog
                - AddEsbLangHeader

            - id: job-crontab-esb
              uri: lb://job-crontab
              predicates:
                - JobEsbV2Path=/api/job/v2/job-crontab/{api_name}
              filters:
                - CheckEsbJwt
                - SetPath=/esb/api/v2/{api_name}
                - RecordEsbAccessLog
                - AddEsbLangHeader

            - id: job-crontab-esb-v3
              uri: lb://job-crontab
              predicates:
                - JobEsbV2Path=/api/job/v3/job-crontab/{api_name}
              filters:
                - CheckEsbJwt
                - SetPath=/esb/api/v3/{api_name}
                - RecordEsbAccessLog
                - AddEsbLangHeader

            - id: job-execute-esb
              uri: lb://job-execute
              predicates:
                - JobEsbV2Path=/api/job/v2/job-execute/{api_name}
              filters:
                - CheckEsbJwt
                - SetPath=/esb/api/v2/{api_name}
                - RecordEsbAccessLog
                - AddEsbLangHeader

            - id: job-execute-esb-v3
              uri: lb://job-execute
              predicates:
                - JobEsbV2Path=/api/job/v3/job-execute/{api_name}
              filters:
                - CheckEsbJwt
                - SetPath=/esb/api/v3/{api_name}
                - RecordEsbAccessLog
                - AddEsbLangHeader

            - id: job-file-gateway-esb-v3
              uri: lb://job-file-gateway
              predicates:
                - JobEsbV2Path=/api/job/v3/job-file-gateway/{api_name}
              filters:
                - CheckEsbJwt
                - SetPath=/esb/api/v3/{api_name}
                - RecordEsbAccessLog
                - AddEsbLangHeader

            - id: job-file-gateway-iam
              uri: lb://job-file-gateway
              predicates:
                - Path=/iam/api/v1/resources/file_source
              filters:
                - RecordIamAccessLog
                - AddEsbLangHeader

            - id: job-ticket-iam
              uri: lb://job-ticket
              predicates:
                - Path=/iam/api/v1/resources/ticket
              filters:
                - RecordIamAccessLog
                - AddEsbLangHeader

            - id: job-analysis-iam
              uri: lb://job-analysis
              predicates:
                - Path=/iam/api/v1/resources/dashboard_view
              filters:
                - RecordIamAccessLog
                - AddEsbLangHeader

            - id: job-manage-iam
              uri: lb://job-manage
              predicates:
                - Path=/iam/api/v1/resources/script,/iam/api/v1/resources/task/template,/iam/api/v1/resources/task/plan,/iam/api/v1/resources/account,/iam/api/v1/resources/whitelist,/iam/api/v1/resources/script/public,/iam/api/v1/resources/tag
              filters:
                - RecordIamAccessLog
                - AddEsbLangHeader

            - id: job-crontab-iam
              uri: lb://job-crontab
              predicates:
                - Path=/iam/api/v1/resources/cron/job
              filters:
                - RecordIamAccessLog
                - AddEsbLangHeader

            - id: job-execute-iam
              uri: lb://job-execute
              predicates:
                - Path=/iam/api/v1/resources/execute/record
              filters:
                - RecordIamAccessLog
                - AddEsbLangHeader
    job:
      gateway:
        login-exemption:
          enable: {{ .Values.gatewayConfig.loginExemption.enable | default false }}
          default-user: {{ .Values.gatewayConfig.loginExemption.defaultUser | default "admin" }}
    server:
      port: {{ .Values.gatewayConfig.containerPort.https }}
      http:
        enabled: true
        port: {{ .Values.gatewayConfig.containerPort.http }}
      ssl:
        keystore:
          type: PKCS12
          path: "file:/data/job/cert/job_server.p12"
          password: ${keystore.password}
        key:
          alias: job_server.p12
        truststore:
          path: file:/data/job/cert/job_server.truststore
          password: ${truststore.password}
    management:
      server:
        port: {{ .Values.gatewayConfig.containerPort.management }}
{{- end}}
